import Anthropic from '@anthropic-ai/sdk';

export interface ContractData {
  client: {
    name: string;
    address: string;
    phone?: string;
    email?: string;
  };
  contractor: {
    name: string;
    address?: string;
    phone?: string;
    email?: string;
    license?: string;
  };
  project: {
    type: string;
    description: string;
    location: string;
    startDate?: string;
    endDate?: string;
  };
  financials: {
    total: number;
    subtotal?: number;
    tax?: number;
    taxRate?: number;
  };
  protections?: Array<{
    id: string;
    title: string;
    content: string;
    category: string;
    riskLevel: string;
  }>;
}

export interface ContractGenerationResult {
  success: boolean;
  html?: string;
  pdfBuffer?: Buffer;
  error?: string;
  metadata?: {
    pageCount: number;
    generationTime: number;
    templateUsed: string;
  };
}

/**
 * Professional Contract Generator in English
 * Based on standard Independent Contractor Agreement format
 */
export class ProfessionalContractGenerator {
  private anthropic: Anthropic;

  constructor() {
    if (!process.env.ANTHROPIC_API_KEY) {
      if (process.env.NODE_ENV === 'production') {
        throw new Error('ANTHROPIC_API_KEY is not configured in production');
      } else {
        console.warn('⚠️ ANTHROPIC_API_KEY not set in contractGenerator. Using a mock for development.');
        this.anthropic = {
          messages: {
            create: async (params: any) => {
              console.log('--- MOCK ANTHROPIC CALL (Contract Generator) ---');
              return {
                id: 'mock_contract_message_id',
                type: 'message',
                role: 'assistant',
                content: [{ type: 'text', text: 'This is a mock contract generated by Anthropic.' }],
                model: 'mock-claude-sonnet-4',
                stop_reason: 'end_turn',
                stop_sequence: null,
                usage: { input_tokens: 10, output_tokens: 10 },
              };
            }
          }
        } as any;
        return;
      }
    }
    
    this.anthropic = new Anthropic({
      apiKey: process.env.ANTHROPIC_API_KEY,
    });
  }

  /**
   * Generate professional contract with PDF generation capability
   */
  async generateProfessionalContract(contractData: ContractData, options: any = {}): Promise<ContractGenerationResult> {
    const startTime = Date.now();
    
    try {
      console.log('🤖 [CONTRACT] Starting professional contract generation...');
      
      // Generate HTML contract
      const html = await this.generateContractHTML(contractData, options.contractorBranding || {});
      
      const generationTime = Date.now() - startTime;
      
      return {
        success: true,
        html,
        metadata: {
          pageCount: this.estimatePageCount(html),
          generationTime,
          templateUsed: 'professional-english'
        }
      };
      
    } catch (error) {
      console.error('❌ [CONTRACT] Error in professional generation:', error);
      return {
        success: false,
        error: error instanceof Error ? error.message : 'Unknown error'
      };
    }
  }

  /**
   * Generate contract HTML with real-time preview functionality
   */
  async generateContractHTML(contractData: ContractData, contractorBranding: any = {}): Promise<string> {
    console.log('📋 [PREVIEW] Generating HTML contract for preview...');
    
    try {
      return this.generateProfessionalHTML(contractData, contractorBranding);
      
    } catch (error) {
      console.error('❌ [CONTRACT-HTML] Error generating HTML:', error);
      return this.generateProfessionalHTML(contractData, contractorBranding);
    }
  }

  /**
   * Generate professional contract HTML in English following standard format
   */
  private generateProfessionalHTML(contractData: ContractData, contractorBranding: any): string {
    // Use personalized contractor branding
    const contractorName = contractorBranding.companyName || contractData.contractor.name || 'Contractor';
    const contractorAddress = contractorBranding.address || contractData.contractor.address || '';
    const contractorPhone = contractorBranding.phone || contractData.contractor.phone || '';
    const contractorEmail = contractorBranding.email || contractData.contractor.email || '';
    const contractorLicense = contractorBranding.licenseNumber || contractData.contractor.license || '';

    // Format current date
    const currentDate = new Date();
    const dayOfMonth = currentDate.getDate();
    const ordinalSuffix = (day: number) => {
      if (day > 3 && day < 21) return 'th';
      switch (day % 10) {
        case 1: return 'st';
        case 2: return 'nd';
        case 3: return 'rd';
        default: return 'th';
      }
    };

    const contractDate = `${dayOfMonth}${ordinalSuffix(dayOfMonth)} day of ${currentDate.toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}`;

    // Generate additional clauses if provided
    let additionalClausesHtml = '';
    if (contractData.protections && contractData.protections.length > 0) {
      additionalClausesHtml = `
        <div class="section-header">ADDITIONAL PROTECTIVE CLAUSES</div>
      `;
      contractData.protections.forEach((clause, index) => {
        const sectionNumber = 20 + index;
        additionalClausesHtml += `
          <p class="numbered-section">
              <span class="section-number">${sectionNumber}.</span> <strong>${clause.title.toUpperCase()}:</strong> ${clause.content}
          </p>
        `;
      });
    }

    return `<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Independent Contractor Agreement</title>
    <style>
        @page {
            size: 8.5in 11in;
            margin: 0.75in 0.75in 1in 0.75in;
            counter-increment: page;
            @bottom-center {
                content: "Page " counter(page) " of 6";
                font-size: 10pt;
                color: #333;
                font-family: 'Times New Roman', serif;
            }
            @bottom-left {
                content: "Independent Contractor Agreement";
                font-size: 9pt;
                color: #666;
            }
            @bottom-right {
                content: "Page " counter(page) " of 6";
                font-size: 9pt;
                color: #666;
            }
        }
        
        body {
            font-family: 'Times New Roman', serif;
            font-size: 12pt;
            line-height: 1.4;
            margin: 0;
            padding: 0;
            color: #000;
            background: white;
        }
        
        .header-section {
            text-align: center;
            margin-bottom: 25px;
        }
        
        .contract-title {
            font-size: 16pt;
            font-weight: bold;
            text-align: center;
            margin: 0 0 15px 0;
            text-transform: uppercase;
            letter-spacing: 1px;
        }
        
        .contract-intro {
            text-align: center;
            margin: 20px 0;
            line-height: 1.6;
        }
        
        .parties-section {
            display: flex;
            justify-content: space-between;
            margin: 25px 0;
            text-align: center;
        }
        
        .party-column {
            flex: 1;
            padding: 0 20px;
        }
        
        .party-title {
            font-weight: bold;
            font-size: 14pt;
            margin-bottom: 10px;
        }
        
        .party-name {
            font-weight: bold;
            margin: 5px 0;
        }
        
        .party-label {
            font-style: italic;
            margin-top: 10px;
        }
        
        .section-header {
            font-size: 12pt;
            font-weight: bold;
            margin: 20px 0 10px 0;
            text-transform: uppercase;
        }
        
        .numbered-section {
            margin: 15px 0;
            text-align: justify;
        }
        
        .section-number {
            font-weight: bold;
            margin-right: 5px;
        }
        
        .bullet-point {
            margin: 8px 0 8px 30px;
            text-align: justify;
        }
        
        .signature-section {
            margin-top: 40px;
            page-break-inside: avoid;
        }
        
        .signature-grid {
            display: flex;
            justify-content: space-between;
            margin-top: 50px;
        }
        
        .signature-column {
            flex: 1;
            margin: 0 10px;
        }
        
        .signature-line {
            border-bottom: 1px solid #000;
            height: 50px;
            margin: 20px 0 5px 0;
        }
        
        .signature-label {
            margin: 5px 0;
            font-size: 11pt;
        }
        
        .page-break {
            page-break-before: always;
        }
        
        .copyright-notice {
            margin-top: 30px;
            text-align: center;
            font-size: 10pt;
            color: #666;
        }
    </style>
</head>
<body>

<div class="header-section">
    <h1 class="contract-title">INDEPENDENT CONTRACTOR AGREEMENT</h1>
</div>

<div class="contract-intro">
    <p><strong>THIS INDEPENDENT CONTRACTOR AGREEMENT</strong> (the "Agreement") is dated this ${contractDate}.</p>
</div>

<div class="parties-section">
    <div class="party-column">
        <div class="party-title">CLIENT</div>
        <div class="party-name">${contractData.client.name}</div>
        <div>${contractData.client.address}</div>
        <div class="party-label">(the "Client")</div>
    </div>
    <div class="party-column">
        <div class="party-title">CONTRACTOR</div>
        <div class="party-name">${contractorName}</div>
        ${contractorAddress ? `<div>${contractorAddress}</div>` : ''}
        <div class="party-label">(the "Contractor")</div>
    </div>
</div>

<div class="section-header">BACKGROUND</div>
<p class="numbered-section">
    <strong>A.</strong> The Client is of the opinion that the Contractor has the necessary qualifications, experience and abilities to provide services to the Client.
</p>
<p class="numbered-section">
    <strong>B.</strong> The Contractor is agreeable to providing such services to the Client on the terms and conditions set out in this Agreement.
</p>

<p style="margin: 20px 0; text-align: justify;">
<strong>IN CONSIDERATION OF</strong> the matters described above and of the mutual benefits and obligations set forth in this Agreement, the receipt and sufficiency of which consideration is hereby acknowledged, the Client and the Contractor (individually the "Party" and collectively the "Parties" to this Agreement) agree as follows:
</p>

<div class="section-header">SERVICES PROVIDED</div>
<p class="numbered-section">
    <span class="section-number">1.</span> The Client hereby agrees to engage the Contractor to provide the Client with the following services (the "Services"):
</p>
<div class="bullet-point">• ${contractData.project.description}</div>

<p class="numbered-section">
    <span class="section-number">2.</span> The Services will also include any other tasks which the Parties may agree on. The Contractor hereby agrees to provide such Services to the Client.
</p>

<div class="section-header">TERM OF AGREEMENT</div>
<p class="numbered-section">
    <span class="section-number">3.</span> The term of this Agreement (the "Term") will begin on the date of this Agreement and will remain in full force and effect until the completion of the Services, subject to earlier termination as provided in this Agreement. The Term may be extended with the written consent of the Parties.
</p>

<div class="page-break"></div>

<div class="section-header">PERFORMANCE</div>
<p class="numbered-section">
    <span class="section-number">4.</span> The Parties agree to do everything necessary to ensure that the terms of this Agreement take effect.
</p>

<div class="section-header">CURRENCY</div>
<p class="numbered-section">
    <span class="section-number">5.</span> Except as otherwise provided in this Agreement, all monetary amounts referred to in this Agreement are in USD (US Dollars).
</p>

<div class="section-header">COMPENSATION</div>
<p class="numbered-section">
    <span class="section-number">6.</span> The Contractor will charge the Client a flat fee of $${contractData.financials.total.toLocaleString()} for the Services (the "Compensation").
</p>

<p class="numbered-section">
    <span class="section-number">7.</span> A retainer of $${Math.round(contractData.financials.total * 0.3).toLocaleString()} (the "Retainer") is payable by the Client upon execution of this Agreement.
</p>

<p class="numbered-section">
    <span class="section-number">8.</span> For the remaining amount, the Client will be invoiced as follows:
</p>
<div class="bullet-point">• The first payment will be after signed contract (30% as upfront cost)</div>
<div class="bullet-point">• The final payment when the project is completed</div>

<p class="numbered-section">
    <span class="section-number">9.</span> Invoices submitted by the Contractor to the Client are due within 30 days of receipt.
</p>

<p class="numbered-section">
    <span class="section-number">10.</span> The Compensation as stated in this Agreement does not include sales tax, or other applicable duties as may be required by law. Any sales tax and duties required by law will be charged to the Client in addition to the Compensation.
</p>

<div class="section-header">REIMBURSEMENT OF EXPENSES</div>
<p class="numbered-section">
    <span class="section-number">11.</span> The Contractor will be reimbursed from time to time for reasonable and necessary expenses incurred by the Contractor in connection with providing the Services.
</p>

<p class="numbered-section">
    <span class="section-number">12.</span> All expenses must be pre-approved by the Client.
</p>

<div class="section-header">INTEREST ON LATE PAYMENTS</div>
<p class="numbered-section">
    <span class="section-number">13.</span> Interest payable on any overdue amounts under this Agreement is charged at a rate of 5.00% per annum or at the maximum rate enforceable under applicable legislation, whichever is lower.
</p>

<div class="page-break"></div>

<div class="section-header">CONFIDENTIALITY</div>
<p class="numbered-section">
    <span class="section-number">14.</span> Confidential information (the "Confidential Information") refers to any data or information relating to the business of the Client which would reasonably be considered to be proprietary to the Client including, but not limited to, accounting records, business processes, and client records and that is not generally known in the industry of the Client and where the release of that Confidential Information could reasonably be expected to cause harm to the Client.
</p>

<p class="numbered-section">
    <span class="section-number">15.</span> The Contractor agrees that they will not disclose, divulge, reveal, report or use, for any purpose, any Confidential Information which the Contractor has obtained, except as authorized by the Client or as required by law. The obligations of confidentiality will apply during the Term and will end on the termination of this Agreement except in the case of any Confidential Information which is a trade secret in which case those obligations will last indefinitely.
</p>

<div class="section-header">OWNERSHIP OF INTELLECTUAL PROPERTY</div>
<p class="numbered-section">
    <span class="section-number">16.</span> All intellectual property and related material, including any trade secrets, moral rights, goodwill, relevant registrations or applications for registration, and rights in any patent, copyright, trademark, trade dress, industrial design and trade name (the "Intellectual Property") that is developed or produced under this Agreement, is a "work made for hire" and will be the sole property of the Client. The use of the Intellectual Property by the Client will not be restricted in any manner.
</p>

<p class="numbered-section">
    <span class="section-number">17.</span> The Contractor may not use the Intellectual Property for any purpose other than that contracted for in this Agreement except with the written consent of the Client. The Contractor will be responsible for any and all damages resulting from the unauthorized use of the Intellectual Property.
</p>

<div class="section-header">RETURN OF PROPERTY</div>
<p class="numbered-section">
    <span class="section-number">18.</span> Upon the expiration or termination of this Agreement, the Contractor will return to the Client any property, documentation, records, or Confidential Information which is the property of the Client.
</p>

<div class="section-header">CAPACITY/INDEPENDENT CONTRACTOR</div>
<p class="numbered-section">
    <span class="section-number">19.</span> In providing the Services under this Agreement it is expressly agreed that the Contractor is acting as an independent contractor and not as an employee. The Contractor and the Client acknowledge that this Agreement does not create a partnership or joint venture between them, and is exclusively a contract for service.
</p>

${additionalClausesHtml}

<div class="page-break"></div>

<div class="signature-section">
    <div class="section-header">SIGNATURES</div>
    <p style="margin: 20px 0; text-align: center;">
        <strong>IN WITNESS WHEREOF</strong> the Parties have duly affixed their signatures under hand and seal on this ${contractDate}.
    </p>
    
    <div class="signature-grid">
        <div class="signature-column">
            <div class="signature-line"></div>
            <div class="signature-label">${contractData.client.name}</div>
            <div class="signature-label">(Client)</div>
        </div>
        <div class="signature-column">
            <div class="signature-line"></div>
            <div class="signature-label">${contractorName}</div>
            <div class="signature-label">(Contractor)</div>
        </div>
    </div>
</div>

<div class="copyright-notice">
    <p>©2025 ${contractorName}</p>
</div>

</body>
</html>`;
  }

  /**
   * Estimate page count based on content length
   */
  private estimatePageCount(html: string): number {
    // Estimate based on content length and average characters per page
    const contentLength = html.replace(/<[^>]*>/g, '').length;
    const avgCharsPerPage = 2800; // Professional layout with proper spacing
    return Math.max(1, Math.ceil(contentLength / avgCharsPerPage));
  }
}

// Export singleton instance
export const professionalContractGenerator = new ProfessionalContractGenerator();